AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Obtém as informações do usuário logado
Resources:
  getuser:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: Obtém as informações do usuário logado
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /customer
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Environment:
        Variables:
          TABLE_NAME: customer
      Layers:
        - ''
